### ISSUE TITLE
Error when running ilastik in headless mode from Matlab

### ISSUE THREAD

**Issue by gcharvin** [ilastik/ilastik#1198] opened 2016-03-16 16:00 UTC
Hi, 
I would like to run ilastike using the headless mode from Matlab in order to integrate the powerful features of Ilastik within my image processing pipeline. However, I get this result when I try to launch ilastik from Matlab : 

> > !/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/run_ilastik.sh --headless
> > INFO ilastik_main: Starting ilastik from "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release".
> > Starting ilastik from "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release".
> > ERROR 2016-03-16 16:56:31,055 excepthooks 23873 140735139775248 Unhandled exception in thread: 'MainThread'
> > ERROR 2016-03-16 16:56:31,057 excepthooks 23873 140735139775248 Traceback (most recent call last):
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 110, in <module>
> >     main()
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 103, in main
> >     ilastik_main.main(parsed_args, workflow_cmdline_args)
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 97, in main
> >     from ilastik.shell.headless.headlessShell import HeadlessShell
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 26, in <module>
> >     from lazyflow.utility import isUrl
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/**init**.py", line 28, in <module>
> >     import utility
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/**init**.py", line 31, in <module>
> >     from roiRequestBatch import RoiRequestBatch
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 27, in <module>
> >     import lazyflow.stype
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/stype.py", line 22, in <module>
> >     import numpy, vigra
> >   File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/vigra/**init**.py", line 106, in <module>
> >     import vigranumpycore
> > ImportError: dlopen(/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/vigra/vigranumpycore.so, 2): Library not loaded: @loader_path/../../.././libtiff.5.dylib
> >   Referenced from: /Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/vigra/vigranumpycore.so
> >   Reason: Incompatible library version: vigranumpycore.so requires version 8.0.0 or later, but libtiff.5.dylib provides version 6.0.0

Thanks in advance for your help, 
Best, 
Gilles

**Comment by stuarteberg** [comment] 2016-03-16 17:05
Duplicate of #1169.  This will be fixed when we release 1.1.9 in the coming days.

**Comment by stuarteberg** [comment] 2016-03-16 17:07
Oops, sorry, I typed that into the wrong issue.  I meant to add that comment to #1197.

**Comment by stuarteberg** [comment] 2016-03-16 17:08
Does this error also occur when you use ilastik's headless mode directly from a Terminal shell?  Or only when called from within a matlab program?

**Comment by gcharvin** [comment] 2016-03-16 20:59
Only when using within Matlab (R2012b). From a terminal, I get no error : 

bash-3.2$ /Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/run_ilastik.sh --headless
INFO ilastik_main: Starting ilastik from "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release".
Starting ilastik from "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release".

**Comment by stuarteberg** [comment] 2016-03-16 23:28
Unfortunately, I don't have a copy of Matlab on OSX to test with.  A colleague just checked the situation on Linux, and it seems to work without issue.

From a glance at the Matlab documentation, it appears there may be a difference between using the [`system`](http://www.mathworks.com/help/matlab/ref/system.html) command and the ["bang"](http://www.mathworks.com/help/matlab/matlab_external/run-external-commands-scripts-and-programs.html) (`!`) syntax used in your example above.

So, does the following command work?

```
system('/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/run_ilastik.sh --headless')
```

**Comment by gcharvin** [comment] 2016-03-17 12:14
Thanks for your reply. Unfortunately , I get the same error using the "system" command . However, I tested it on a different MacOS computer with Matlab R2015a an it worked fine. 
I don't get why the version of Matlab affects the loading of libraries for ilastik....

**Comment by k-dominik** [comment] 2019-09-05 09:29
closing this - please open a new issue if you run into problems using current ilastik/matlab combinations!

**Closed by k-dominik** 2019-09-05 09:29 UTC
