### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by Andrea-virology** [ilastik/ilastik#1178] opened 2016-01-22 11:51 UTC
Hi everyone
[.ilastik_log.txt](https://github.com/ilastik/ilastik/files/100710/default.ilastik_log.txt)
I downloaded illastiks and applied for the cplex license. 
I wanted to start with the pixel classification. However I cannot even load in the raw data, but get the following error message:

Python argument types in vigra.impex.readImage(str) did not match C++ signature:
ReadImage(char const* _ptr64 filename, class boost::Python::api::object dtype=’FLOAT’, unsigned int index=0, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> > order=”)

(Advanced information about this error may be found in the log file C:\Users\Andrea\.ilastik_log.txt)

I attached the log file. 
What did I do wrong?

Andrea

**Comment by stuarteberg** [comment] 2016-01-22 14:07
This appears to be a duplicate of #1176.  We'll be making a new release soon.

**Comment by akreshuk** [comment] 2016-03-16 13:09
resolved as reported in #1176

**Closed by akreshuk** 2016-03-16 13:09 UTC
