### ISSUE TITLE
DLL import error when trying to start ilastk 1.1.3

### ISSUE THREAD

**Issue by sebi06** [ilastik/ilastik#1067] opened 2015-01-07 10:56 UTC
Hi guys,

I just installed ilastik 1.1.3 on my Windows7 64bit system and wanted to start it but got the errors below. I tried to figure out what the problem is but could not solve it so far...

Cheers Sebastian

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Program Files\ilastik-1.1.3>ilastik.bat
WARNING: CPLEX is not in the PATH -- chaingraph tracking will be unavailable.
Loading ilastik from "C:\Program Files\ilastik-1.1.3\ilastik"
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik.py", line 24, in
<module>
    import ilastik_main
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik_main.py", line 4,
 in <module>
    import ilastik.config
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik\__init__.py", lin
e 125, in <module>
    _check_depends()
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik\__init__.py", lin
e 119, in _check_depends
    import h5py
  File "C:\Python27\lib\site-packages\h5py\__init__.py", line 10, in <module>
    from h5py import _errors
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

C:\Program Files\ilastik-1.1.3>

**Comment by sebi06** [comment] 2015-01-07 11:09
Additional information:

I used:

http://www.hdfgroup.org/ftp/HDF5/current/bin/windows/hdf5-1.8.14-win64-vs2012-shared.zip

to install HDF5 and when I am using python I have installed:

h5py‑2.3.1.win‑amd64‑py2.7.exe from http://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py

But ilastik is having its own h5py right? (sorry if that question is nor very smart...)

Sebi

**Comment by burcin** [comment] 2015-01-08 12:58
Hi Sebi,

you're on the right track, ilastik is picking up the h5py version that you installed instead of the that is included in the binary. I don't know how this can happen, since we actively try to prevent this situation by setting `PATH` and `PYTHONPATH` in `ilastik.bat`.

Can you replace `ilastik.bat` in your install with [this version](http://files.ilastik.org/ilastik.bat) and post the output of this command:

    ilastik.bat run "import sys; print sys.executable; print sys.path"

For the record, the `ilastik.bat` file linked above adds this section above the `:testing` line:

    :run
    echo ----------------------------
    echo Running python command...
    "%INSTALL_DIR%python\python" -c %2
 
    goto :end

**Comment by sebi06** [comment] 2015-01-13 07:02
Hi,

here is the output:
----------------------------------------------------------------------------------------------------------

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Program Files\ilastik-1.1.3>ilastik.bat run "import sys; print sys.executable
; print sys.path"
WARNING: CPLEX is not in the PATH -- chaingraph tracking will be unavailable.
----------------------------
Running python command...
C:\Program Files\ilastik-1.1.3\python\python.exe
['', 'C:\\Python27\\lib\\site-packages\\pyinstaller-2.1-py2.7.egg', 'C:\\Python2
7\\lib\\site-packages\\distribute-0.7.3-py2.7.egg', 'C:\\Python27\\lib\\site-pac
kages\\mpltools-0.2dev-py2.7.egg', 'C:\\Python27\\lib\\site-packages\\scikit_tra
cker-0.3.dev-py2.7-win-amd64.egg', 'C:\\Python27\\lib\\site-packages\\trackpy-0.
6.0.dev-py2.7.egg', 'C:\\Python27\\lib\\site-packages\\scikit_image-0.11dev-py2.
7-win-amd64.egg', 'C:\\Python27\\lib\\site-packages\\yolk-0.4.3-py2.7.egg', 'C:\
\Python27\\lib\\site-packages\\pylint-1.2.0-py2.7.egg', 'C:\\Python27\\lib\\site
-packages\\astroid-1.2.1-py2.7.egg', 'C:\\Python27\\lib\\site-packages\\logilab_
common-0.62.1-py2.7.egg', 'C:\\Python27\\lib\\site-packages\\colorama-0.3.1-py2.
7.egg', 'C:\\Python27\\lib\\site-packages\\pep8-1.5.7-py2.7.egg', 'C:\\Python27\
\lib\\site-packages\\csvkit-1.0.0-py2.7.egg', 'C:\\Python27\\lib\\site-packages\
\dbf-0.94.003-py2.7.egg', 'C:\\Python27\\lib\\site-packages\\openpyxl-2.1.0-py2.
7.egg', 'C:\\Python27\\lib\\site-packages\\sqlalchemy-0.9.7-py2.7-win-amd64.egg'
, 'C:\\Python27\\lib\\site-packages\\jdcal-1.0-py2.7.egg', 'C:\\Python27\\lib\\s
ite-packages\\sortedcontainers-0.9.1-py2.7.egg', 'C:\\Program Files\\ilastik-1.1
.3\\ilastik\\lazyflow', 'C:\\Program Files\\ilastik-1.1.3\\ilastik\\volumina', '
C:\\Program Files\\ilastik-1.1.3\\ilastik\\ilastik', 'C:\\Program Files\\ilastik
-1.1.3\\python\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\P
ython27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Program Files\\ilasti
k-1.1.3\\python', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages', 'C:\\Pytho
n27\\lib\\site-packages\\win32', 'C:\\Python27\\lib\\site-packages\\win32\\lib',
 'C:\\Python27\\lib\\site-packages\\Pythonwin', 'c:\\python27\\lib\\site-package
s', 'C:\\Python27\\lib\\site-packages\\vlfd', 'C:\\Python27\\lib\\site-packages\
\wx-2.8-msw-unicode']

C:\Program Files\ilastik-1.1.3>

**Comment by burcin** [comment] 2015-01-13 10:46
It looks like you have `PYTHONHOME` set to your system python install. I put up a new [ilastik.bat](http://files.ilastik.org/ilastik.bat) that also overwrites this variable. Can you replace the existing `ilastik.bat` with this version and try running ilastik again?

**Comment by sebi06** [comment] 2015-01-14 12:22
Hi,

now it works. Thanks for the help.

Sebi

**Comment by ukoethe** [comment] 2015-01-14 15:19
@burcin : Your changes to `ilastik.bat` make sense, please commit them (perhaps as a pull request for detailed reviewing)..

**Comment by stuarteberg** [comment] 2015-03-31 23:52
@ukoethe, it looks like @burcin's commit from above was never merged into `ilastik-build-win64`.  Does it need to be?  If not, you can close this issue.  (Assigning it to you :-)

**Comment by ukoethe** [comment] 2015-04-08 16:43
The problem is that the fix doesn't work properly. Resolved via https://github.com/ilastik/ilastik-build-win64/commit/df4c0378d968a6ae43560fa2aab477bb5200de61

**Closed by ukoethe** 2015-04-08 16:43 UTC
