### ISSUE TITLE
layer export error message

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1060] opened 2014-12-07 20:16 UTC
On windows, the layer export button (at least when selection jpeg as output) tries to write to the ilastik installation directory. This results in a scary-looking error message about "precondition violation" etc. 

Make it more human-readable by saying sth like "Do not have permission to write to this directory. Please select a different directory."

**Comment by stuarteberg** [comment] 2015-03-29 15:36
Possible duplicate of #920

**Comment by stuarteberg** [comment] 2017-03-01 02:41
Should be fixed via 2ebbfb42b62e3997d919ab84f65077e7f34e59dc

**Closed by stuarteberg** 2017-03-01 02:41 UTC
