### ISSUE TITLE
Issue with headless processing in windows

### ISSUE THREAD

**Issue by ohudson1** [ilastik/ilastik#2591] opened 2022-07-14 00:29 UTC
## Describe the bug
Ilastik functions fine when running the prediction export inside the app, and can batch process successfully. However, when running it headless, an error occurs and prevents the export, or perhaps the loading of the project entirely.

## Expected behavior
Please add a clear and concise description of what you expected to happen.
Simply run a headless version of my ilastik project with a batch processing output of a separate directory. 

## To Reproduce
Within the ... workflow
1. Train a project
2. start terminal or command prompt
3. .\ilastik.exe --headless --project="directory\project.ilp" --output_format=tiff --output_filename_format={nickname}_results.tiff --"directory_of_desired_batch_process\*.png"

## Error message/traceback

```pytb
INFO ilastik.shell.projectManager: Opening Project: project.ilp
WARNING dataset.py(313): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING 2022-07-13 20:17:13,428 pixelClassificationWorkflow 5624 17588 Unused command-line args: ['--directory_of_batch*.png']
WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING 2022-07-13 20:17:16,132 pixelClassificationWorkflow 5624 17588 Your project file has no classifier.  A new classifier will be trained for this run.
INFO ilastik.workflows.pixelClassification.pixelClassificationWorkflow: Beginning Batch Processing
ERROR 2022-07-13 20:17:16,133 log_exception 5624 17588 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 467, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 382, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 64, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 121, in run_export
    self.dataExportApplet.post_process_entire_export()
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 398, in post_process_entire_export
    self.pcApplet.topLevelOperator.FreezePredictions.setValue(self.freeze_status)
AttributeError: 'PixelClassificationWorkflow' object has no attribute 'freeze_status'

ERROR 2022-07-13 20:17:16,135 log_exception 5624 17588 Project could not be loaded due to the exception shown above.
```

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: 1.3.3post3
 - OS: Windows 10
 
 I have an inkling that this functions fine in a macOS, so likely it is windows specific.

**Comment by k-dominik** [comment] 2022-07-18 14:10
Hey @ohudson1,

sorry that you're running into this. I'm not sure the error we are seeing here gives the right hints. But I assume you are on windows and want to process a bunch of input files that you specify using the `*` (asterisk) character - is that correct? On windows cmd this doesn't work! It's a feature of unix shells that they replace that term by all the files names after one another that match that pattern. If you give it in windows, ilastik will try to interpret the data as a stack (or maybe that is exactly what you want, in that case I'd look more into it).

Otherwise, per coincidence I checked today how one could do this on windows and found that it should be possible using powershell rather than cmd:

```
.\ilastik.exe --headless <more_args> (GET-ITEM .\*.png)
```

**Comment by k-dominik** [comment] 2022-07-27 09:16
Hello @ohudson1,

I'll close this issue for now, as I don't think there is anything actionable left on our side. Please reopen, or open a new issue if headless processing still doesn't work as expected!

Cheers
Dominik

**Comment by patrickaoude** [comment] 2022-07-27 23:36
@k-dominik sorry to revive this just after it was closed, but I am experiencing the same problem although there is no * usage.

Here's my command:

`C:\Program Files\ilastik-1.3.3post3\ilastik.exe --headless --project=C:\Users\Patrick\Desktop\Cecilia2Patrick\UTI_EPI_plusNTcData_EdU_Pixel_Classifier_06302022.ilp --output_format="tiff sequence" --output_filename_format="C:\Users\Patrick\Desktop\Cecilia2Patrick\small\tiff_probability_maps\{nickname}_{slice_index}_EdU_probability.tiff"`

I have tried with another project and have the same error. Here's that command:

`
C:\Program Files\ilastik-1.3.3post3\ilastik.exe --headless --project=C:\Users\Patrick\Desktop\Cecilia2Patrick\MyProject17258_Classifier_Train_NTc_06292022.ilp --output_format="tiff sequence" --output_filename_format="C:\Users\Patrick\Desktop\Cecilia2Patrick\small\tiff_probability_maps\{nickname}_{slice_index}_17258_probability.tiff"`

Here's the full output for the error:

`C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\classifiers\__init__.py:20: UserWarning: init: Could not import tiktorch classifier
  warnings.warn("init: Could not import tiktorch classifier")
INFO ilastik_main: Starting ilastik from "C:\Program Files\ilastik-1.3.3post3".
Starting ilastik from "C:\Program Files\ilastik-1.3.3post3".
WARNING 2022-07-27 19:33:23,884 opConservationTracking 20220 21072 Could not find any ILP solver
WARNING 2022-07-27 19:33:23,931 opStructuredTracking 20220 21072 Could not find any ILP solver
WARNING 2022-07-27 19:33:23,931 structuredTrackingWorkflow 20220 21072 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
INFO ilastik.shell.projectManager: Opening Project: C:/Users/Patrick/Desktop/Cecilia2Patrick/MyProject17258_Classifier_Train_NTc_06292022.ilp
WARNING dataset.py(313): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
INFO ilastik.workflows.pixelClassification.pixelClassificationWorkflow: Beginning Batch Processing
ERROR 2022-07-27 19:33:37,312 log_exception 20220 21072 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 467, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 382, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 64, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 121, in run_export
    self.dataExportApplet.post_process_entire_export()
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 398, in post_process_entire_export
    self.pcApplet.topLevelOperator.FreezePredictions.setValue(self.freeze_status)
AttributeError: 'PixelClassificationWorkflow' object has no attribute 'freeze_status'

ERROR 2022-07-27 19:33:37,312 log_exception 20220 21072 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2022-07-27 19:33:40,200 excepthooks 20220 21072 Unhandled exception in thread: 'MainThread'
ERROR 2022-07-27 19:33:40,200 excepthooks 20220 21072 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik.py", line 134, in <module>
    main()
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik.py", line 128, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik_main.py", line 170, in main
    f(shell)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik_main.py", line 347, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\shell\headless\headlessShell.py", line 125, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 467, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 382, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 64, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 121, in run_export
    self.dataExportApplet.post_process_entire_export()
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 398, in post_process_entire_export
    self.pcApplet.topLevelOperator.FreezePredictions.setValue(self.freeze_status)
AttributeError: 'PixelClassificationWorkflow' object has no attribute 'freeze_status'`

I'll see if I can figure this out myself, but if you have any suggestions for a solution please let me know. The problem is surprising since this script ran fine for me recently. I'm not sure if a Windows update could have contributed some change that's caused this runtime error.

**Comment by k-dominik** [comment] 2022-07-28 12:23
Sorry for closing prematurely - and thank you for following up!. I'm puzzled - I'm not sure yet how it can come to this error - investigating.

**Comment by k-dominik** [comment] 2022-07-28 12:45
I'm curious - did you leave out the input image from the command on purpose here (not that this causes the error)...

So I've tried a bit now to make ilastik go into this error state, but I couldn't (and from code I'm puzzled it can happen at all). So, would you maybe willing to share your project file and one input data set so I could try it? If so, here's a file drop that you could upload to (expires Sat.): https://oc.embl.de/index.php/s/V0H8l7Ys1oILZOA

**Comment by patrickaoude** [comment] 2022-07-28 14:09
@k-dominik thanks for your reply, your question about the input image made me realize that my command was missing the h5 input that I previously provided. My command is generated and assumes certain naming conventions that some new test images were not following, so they were not picked up and used as inputs. I'm not sure of the type of setup that doesn't require any input image, but I was under the impression I should have been providing an input image in my case.

Thanks again for your help

**Comment by k-dominik** [comment] 2022-07-29 08:57
Hi @patrickaoude,

do you think you can share the project (via the above link?)? Otherwise, I'm not sure I can reproduce --> fix the problem

**Comment by patrickaoude** [comment] 2022-07-29 14:40
Hi @k-dominik I fixed the problem by providing the input image as part of the command. A naming mismatch caused my script's glob/regex to miss the new input file. Thanks for your time

**Comment by k-dominik** [comment] 2022-07-29 19:45
Hey @patrickaoude, thanks  a lot for the feedback. Still I would have _loved_ to reproduce the issue :) Please don't hesitate to open a new issue if something else comes up!

**Closed by k-dominik** 2022-07-29 19:45 UTC

**Comment by patrickaoude** [comment] 2022-07-30 16:04
@k-dominik I would have uploaded it earlier but unfortunately it's not my code to share (it belongs to a peer). Any future issues I'll try to provide as much information as I can. Thanks!
