### ISSUE TITLE
object classification: live update n/a after labeling first objects per right-click

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1077] opened 2015-02-05 11:08 UTC
In object classification, when labeling the first objects via right-clicking an object and selecting a class, the live-update button remains grayed out. This is still true after clicking on the label class selection in the labeling widget. 

The only way to activate live update seems to be to label objects of either class first by using the label selection widget on the LHS of the screen.

**Comment by k-dominik** [comment] 2018-07-16 07:33
Albeit not being mentioned in any commit, I cannot reproduce this issue anymore - so I'm closing this one.

**Closed by k-dominik** 2018-07-16 07:33 UTC
