### ISSUE TITLE
Overwriting and deleting of exported files does not work in Windows

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1547] opened 2017-06-14 09:16 UTC
Failed overriding error message:
```
ERROR 2017-06-14 11:12:07,851 log_exception 2812 4228 Traceback (most recent call last):
  File "C:\conda\envs\ilastik-dev\ilastik-meta\ilastik\ilastik\applets\dataExport\dataExportGui.py", line 393, in exportSlots
    opLaneView.run_export()
  File "C:\conda\envs\ilastik-dev\ilastik-meta\ilastik\ilastik\applets\dataExport\opDataExport.py", line 269, in run_export
    self._opFormattedExport.run_export()
  File "C:\conda\envs\ilastik-dev\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opFormattedDataExport.py", line 242, in run_export
    self._opExportSlot.run_export()
  File "C:\conda\envs\ilastik-dev\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opExportSlot.py", line 234, in run_export
    export_func()
  File "C:\conda\envs\ilastik-dev\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opExportSlot.py", line 242, in _export_hdf5
    os.remove(export_components.externalPath)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:/Users/Fynn/Downloads/ilastik/flyBowlMovie200/flyBowlMovie200_Probabilities.h5'

ERROR 2017-06-14 11:12:07,852 log_exception 2812 4228 Failed to generate export file:
C:/Users/Fynn/Downloads/ilastik/flyBowlMovie200/flyBowlMovie200_Probabilities.h5/exported_data
[Error 32] The process cannot access the file because it is being used by another process: 'C:/Users/Fynn/Downloads/ilastik/flyBowlMovie200/flyBowlMovie200_Probabilities.h5'
```

**Comment by k-dominik** [comment] 2017-06-16 07:41
Okay I think we have seen something similar in the hdf5 stack reader tests on windows. While it is not a problem to delete/overwrite a file that is still open on linux and mac, this is not supported on Windows. The key here would be to find out where the file is being kept open and then see where it might make sense to close it.

**Comment by mthaak** [comment] 2018-05-14 09:56
I also get this error on Windows 10 when I try to do "Export All" under the Object Information Export step for Pixel Classification + Object Classification. When I Export for each image separately, there appears to be no problem.

**Comment by k-dominik** [comment] 2019-08-29 07:48
The problem is `OpDataExport` that is opening the file for the `ImageOnDisk` slot. Somehow the `_opImageOnDiskProvider` is still connected.

See https://github.com/ilastik/ilastik/blob/master/ilastik/applets/dataExport/opDataExport.py#L254

**Closed** 2019-10-01 07:49 UTC
Labels: data-export, os:windows
