### ISSUE TITLE
Different results between windows / unix versions

### ISSUE THREAD

**Issue by patriciagarciac** [ilastik/ilastik#1649] opened 2017-11-17 14:36 UTC
Dear Ilastik developers,

First of all, thank you for developing such a nice and useful tool :). I would like to share a couple of things we have experienced using a different version of Ilastik. Just to say that we are using the Autoconetxt workflow to segment synchrotron X-ray phase-contrast images. 

1) When you have generated your .ilp file with a version, example 1.2.1 of Ilastik, but later you have upgraded your ilastik version to 1.2.2 and use the same file to segment the dataset in headless mode, the results of the segmentation are wrong. Why? This means also, that we can not upgrade Ilastik anymore because if not, all the files that we already have they cannot be used and the newer versions of Ilastik?

2) Also we have seen that, even by using and installing exactly the same version of Ilastik (1.2.2) in two different computers: one with windows and the other with Linux, the file that we generated with the windows version, when we run the headless mode segmentation in the whole volume in the Linux version gave us also wrong results. SO are the different SO version incompatible also?

Thank you very much in advance for your help & support.

**Comment by ilastikdev** [comment] 2017-11-17 16:38
Hi Patricia,

In general we do not support backward compatibility of project files  
between different ilastik versions. We might be able to modify the old  
version to give you correct results in the newer version of ilastik.  
Please send us the ilp file. Our autocontext expert is away at the  
moment, but we will get back to you asap.

We strive to have the same code running on all three supported  
platforms. Send us the ilp file in question and we will see what is  
the real reason for different/false segmentation results on Linux from  
your Windows autocontext project.

Janez.


Quoting patriciagarciac <notifications@github.com>:

**Comment by patriciagarciac** [comment] 2017-11-21 07:58
Hi Janez,

It's a pity that you do not support backward compatibility, because you're updating Ilasitk often, and this means that we cannot use the new versions. I put the ilastik and some example images in a Dropbox folder. How can I send it privately?

Best,

Patricia

**Comment by akreshuk** [comment] 2017-11-21 11:00
Hi Patricia,

Just to clarify: we do not support backward compatibility in the sense that we can not guarantee compatibility of the files with the next version as we can only test so much. So far, it has worked almost always and for the few exceptions we wrote specific converters and dealt with the older files this way. So don't be afraid of upgrading, we are making things better all the time!

However, the behavior you are observing has nothing to do with backward compatibility. It should never have different results when running on different machines, regardless of version numbers. Some things I can think of: 1) if you have very few labels, the inherent randomness of the Random Forest can play a role, 2) depending on how precisely you evaluate your segmentation, the small differences in prediction probabilities can also sum up. This could be caused by the fact that we have a very fast feature computation library which we only ported to Windows in the most recent release 1.3. So the feature computation should have given the same results up to some precision level + Random Forest introduces some variability --> if you are watching for pixelwise equality, it could be a bit different.  

In any case, it sounds wrong and I would really like to take a look. Could you send the Dropbox link to team@ilastik.org?

Thanks,
Anna

**Comment by k-dominik** [comment] 2023-10-18 14:35
xref: #2314 (for a more in depth discussion on platform differences). Closing.

**Closed by k-dominik** 2023-10-18 14:35 UTC
