### ISSUE TITLE
locate previously labeled slice(s)/region(s) in 3D stack file

### ISSUE THREAD

**Issue by czhci** [ilastik/ilastik#197] opened 2013-03-19 14:34 UTC
If the slice number or region indices were not noted, apart from scrolling slice by slice through the entire stack, is there an apparent way to quickly locate previously done labels from a 3D stack?

**Comment by akreshuk** [comment] 2017-05-23 11:22
Duplicate of #109.

**Closed by akreshuk** 2017-05-23 11:22 UTC
Labels: enhancement, pixelClassification
