### ISSUE TITLE
Rotating image rotates tiles individually

### ISSUE THREAD

**Issue by maierl** [ilastik/ilastik#1314] opened 2016-08-02 12:26 UTC
In ilastik 1.2.0 rc7, when I select the rotate image buttons, the current view rotates every tile individually, but they are not repositioned. After changing the slice, the tiles are updated correctly.

so this is what happens to a 2x2 tile view (every letter represents a tile):
```
old   new

-<    |^
>~    vs
```

but it should be

```
old   new

-<  v|
>~  s^
```

**Comment by stuarteberg** [comment] 2016-08-15 22:11
(This is a duplicate of #1290.)

Now fixed via ilastik/volumina@d8c0bd45b07e7ad182b9f685bb7dd484248fef78.  Thank goodness for `git bisect`.

**Closed by stuarteberg** 2016-08-15 22:11 UTC
