### ISSUE TITLE
Batch processing on image stacks

### ISSUE THREAD

**Issue by etmckinley** [ilastik/ilastik#1848] opened 2018-10-01 15:48 UTC
I want to run pixel classification of image stacks with multiple channels. Training can be done by changing the axes from 'zyx' to 'cyx'. however this can't seem to be done when loading the same multichannel tiffs in to the batch processer.

Version: Ilastik 1.3.0 for OsX

**Comment by k-dominik** [comment] 2018-10-02 08:50
Hi @etmckinley ,

really sorry that you see this error there. Just to clarify, do you mean by batch processor the batch processing applet? Or do you invoke ilastik in the headless mode from the command line?

could I ask you to try it with the latest beta, there has been done a lot of work with the internal representation of the axes. You can get it [here for the OsX](http://files.ilastik.org/ilastik-1.3.2b3-OSX.tar.bz2)

**Comment by etmckinley** [comment] 2018-10-02 14:58
The applet. I'd like to specify that my stack should be 'cyx'.

Trying the beta actually makes it worse. I have a 30x2048x2048 tiff stack (i.e. 30 channels) that I can't even import correctly now. By default it opens as 'zyxc' (20,2048,2048,1) and I can't change it to 'cyxz' or 'cyx' without this error: 
![image](https://user-images.githubusercontent.com/32343131/46357117-bbb59b00-c629-11e8-94b7-55594d32a7fa.png)

**Comment by k-dominik** [comment] 2018-10-02 16:20
meh :/
okay, so this seems to be the same as https://github.com/ilastik/ilastik/issues/1845 . This is actually fixed and ready to be merged in #1847 . We'll make available a new binary this week.

**Comment by etmckinley** [comment] 2018-10-02 17:22
Thanks, looks like the same issue. Will this apply to the batch processing applet too?

**Comment by k-dominik** [comment] 2018-10-16 08:32
@etmckinley we have a new release up that includes the fix: http://ilastik.org/download.html
I have confirmed that the axes reordering also applies to the batch processing applet. Please let us know if it works with your data!

**Comment by etmckinley** [comment] 2018-10-16 16:34
The batch processing works when loading a project made with 1.3.0. But in 1.3.2 I can't load in a multi-channel tiff correctly. I want to set the axes to c,y,x,z but it is not letting me set c as the first axis.

**Comment by k-dominik** [comment] 2018-10-16 16:42
Have you tried just setting it to 'cyx'?

**Comment by etmckinley** [comment] 2018-10-16 16:52
I get this alert when doing it, but it still works.
![image](https://user-images.githubusercontent.com/32343131/47032832-ee3aba00-d138-11e8-96df-b452c8c33e37.png)

**Comment by k-dominik** [comment] 2018-10-17 07:28
That is really unfortunate - I thought we tested it on really comparable data. Could you maybe make us a sample image available, so that we can reproduce the problem? If so, it would be great if you could send us a link to team@ilastik.org .

**Closed** 2019-08-29 15:19 UTC
