### ISSUE TITLE
Failed to export: "Index 1 is out of bounds [...] "

### ISSUE THREAD

**Issue by LipidMiles** [ilastik/ilastik#2279] opened 2020-07-25 12:27 UTC
Hi.
I'm trying out Ilastik and it looks great so far!
But I got an issue with the Export of my data in CSV. For one picture it worked perfectly, now nothing is happening (Configure Feature Table Export). When I try to export in hdf5 for example (Choose Export Image Settings..) I got this error. Maybe one of you got an idea what I am doing wrong?
It seems like an excel-file is created and deleted at the same moment.

Thank you.
M

![image](https://user-images.githubusercontent.com/68777900/88456960-e322cb00-ce82-11ea-85f8-47b7b883fb10.png)

**Comment by k-dominik** [comment] 2020-07-27 07:11
Hi @LipidMiles ,

it appears you're running into a bug (that we really should fix). I think the problem is that the image you are processing does not have _any_ objects on it. A case we didn't account for...

**Comment by k-dominik** [comment] 2020-07-27 07:52
tiny update: this appears to be fixed in 1.3.3post3. What version of ilastik are you using? (also are you in the combined Pixel and Object Classification workflow, or in Object Classification)?

**Closed** 2020-09-02 06:42 UTC
