### ISSUE TITLE
Ilastik stops responding when trying to save a model

### ISSUE THREAD

**Issue by sebherbert** [ilastik/ilastik#2606] opened 2022-08-25 11:31 UTC
## Describe the bug
Ilastik stops responding when trying to save a model. Confirmed with the command save as with a new model to be sure. Tested with Ilastik 1.3.2 and 1.3.3post3 on 3 separate Windows 10 machines. The problem couldn't be reproduced on Linux machines.

## To Reproduce
-> Open the bat-cochlea-volume sample from Fiji
-> Export as H5 using Ilastik/Export HDF5 (no compression) [final dataset](https://drive.switch.ch/index.php/s/clXHOBeSqETgBZP)
-> Open Ilastik 1.3.3post3
-> Select Pixel classification project
-> input cochlea.h5 image
-> select all features
-> Provide a few pixel examples for label 1 & 2
-> Activate live update
-> click Project/Save Project as...
-> Ilastik stops responding

## Error message/traceback
Ilastik logs: 
for Ilastik 1.3.3post3: 
- [ilastik_v1.3.3_log.txt](https://github.com/ilastik/ilastik/files/9424108/ilastik_v1.3.3_log.txt)
- [ilastik_v1.3.3post3_console_output.txt](https://github.com/ilastik/ilastik/files/9424162/ilastik_v1.3.3post3_console_output.txt)

for Ilastik 1.3.2: 
- [ilastik_v1.3.2_log.txt](https://github.com/ilastik/ilastik/files/9424109/ilastik_v1.3.2_log.txt)
- [ilastik_v1.3.2_console_utput.txt](https://github.com/ilastik/ilastik/files/9424165/ilastik_v1.3.2_console_utput.txt)

## Desktop (please complete the following information):
 - ilastik version: Surprisingly this happened on both old and newly deployed versions of the soft, the 1.3.2 version is an old installed, and the tests on 1.3.3post3 where both on freshly downloaded Ilastik and old install.
 - OS: Windows 10

Hopefully I haven't missed something obvious :)
Let me know if I can add anything or test something else.

Best,
Sebastien

**Comment by k-dominik** [comment] 2022-08-25 12:06
Hello @sebherbert,

thank you for the detailed report - very easy to reproduce. I tested this with both versions and can confirm, that doing save-as hangs for me as well.. However, in the current release candidate 1.4.0rc2 it seems to be working fine. Could you maybe try it?

Cheers
Dominik

**Comment by sebherbert** [comment] 2022-08-25 13:10
Thanks!
Seems good with the last 1.4.0rc2 version indeed!
If you believe this version is stable enough to be deployed as the standard version across our University, I can start to get the release candidate on our systems.

**Comment by k-dominik** [comment] 2022-08-25 13:40
Hey @sebherbert,

it's in a way pretty stable already, but also not complete and we will be finalizing it in the next weeks (e.g. with your contribution :D).
If it were easy to redeploy, then I'd say, sure, go for it. If you'd rather not do it too often, then maybe wait 2-4 weeks.

Cheers

I'll close this issue, as it's fixed in the current main branch, and we won't do backports for 1.3.2 or 1.3.3 anymore.

**Closed by k-dominik** 2022-08-25 13:40 UTC

**Comment by sebherbert** [comment] 2022-08-25 13:43
Ok thanks, I'll see how complex this deployment would be for us.
I'll go back to it to my button then ;)
