### ISSUE TITLE
Problem saving "Pixel Classification" project file

### ISSUE THREAD

**Issue by alyst** [ilastik/ilastik#2169] opened 2020-01-13 20:12 UTC
## Describe the bug
The "Pixel classification" project contains 6 *cxy* 32bit (green and red channels) images (loaded from *HDF5* files). All images are of the same dimension.
There's 6 classification labels. When I try to save the project, I get *Object dtype dtype('O') has no native HDF5 equivalent*.

## Expected behavior
The project is correctly saved, no warning is given.

## To Reproduce
I had not tried to reproduce. At the moment ilastik with unsaved project is running, and I'm concerned whether it's possible to save it.
I can provide all *.h5* files for the source images and the exported labels.

[Example of an H5 image](https://github.com/ilastik/ilastik/files/4055591/ATP6V0D1_F4_1_00d00h00m.zip).

## Error message/traceback

```pytb
ERROR 2020-01-13 18:35:34,290 log_exception 366756 140675941132032 Project Save Action failed due to the exception shown above.
ERROR 2020-01-13 18:39:05,051 log_exception 366756 140675798521600 Traceback (most recent call last):
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 241, in _serialize
    self._saveValue(group, name, slot.value)
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 371, in _saveValue
    sg = group.create_dataset(name, data=data)
  File "/opt/ilastik/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/opt/ilastik/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1707, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 293, in saveProject
    serializer.serializeToHdf5(self.currentProjectFile, self.currentProjectPath)
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1110, in serializeToHdf5
    ss.serialize(topGroup)
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 213, in serialize
    self._serialize(group, self.name, self.slot)
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 243, in _serialize
    self._saveValue(group, name, slot(()).wait())
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 371, in _saveValue
    sg = group.create_dataset(name, data=data)
  File "/opt/ilastik/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/opt/ilastik/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1707, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

## Screenshots
Not necessary.

## Desktop (please complete the following information):
 - ilastik version: *1.3.3post2*
 - OS: *ArchLinux*

**Comment by k-dominik** [comment] 2020-01-30 08:21
Hi @alyst,

thanks a lot for making us aware of this issue! I downloaded your example file (thanks again!) and tried to nudge it to do the same for me. However, I couldn't get ilastik to fail for me. So yes, could you please provide us with the rest of the data, and the labels? (maybe via a link to team@ilastik.org ).

Best (and sorry for the delayed response).

**Comment by alyst** [comment] 2020-01-30 08:24
@k-dominik Thanks for the response! I've also tried to reproduce it by loading the same files, and didn't see this error. Probably it's some specific sequence of interactions with UI, but it would be very hard to replicate.

**Comment by k-dominik** [comment] 2020-01-30 09:37
Okay, thank you very much for clearing it up. And good to know that it works now. I'm closing this for now, since we cannot identify a cause.

**Closed by k-dominik** 2020-01-30 09:37 UTC

**Comment by jjerphan** [comment] 2020-07-29 11:34
Hello,

I do meet a similar problem in a 2-stage Autocontext worflow.
I've put some logging on the serialization classes in `lazyflow`, and it looks like an object (whose serialization is not supported by h5) is being serialized. From the trace I get, an instance of `OpFormattedDataExport.FormatSelectionErrorMsg` might be this object:

```
ERROR 2020-07-29 11:54:40,020 slot 7664 139953135314752 Number of Downstream_slots: 1
ERROR 2020-07-29 11:54:40,020 slot 7664 139953135314752 OpFormattedDataExport.FormatSelectionErrorMsg []:       {_ready : True, NOTREADY : None, shape : (1,), dtype : <class 'object'>, has_mask : None, _dirty : False}
ERROR 2020-07-29 11:54:40,020 slot 7664 139953135314752 setDirty called
ERROR 2020-07-29 11:54:40,020 slot 7664 139953135314752 self.stype.isConfigured
ERROR 2020-07-29 11:54:40,021 slot 7664 139953135314752 Number of Downstream_slots: 0
ERROR 2020-07-29 11:54:40,021 slot 7664 139953135314752 setDirty called
ERROR 2020-07-29 11:54:40,021 slot 7664 139953135314752 self.stype.isConfigured
ERROR 2020-07-29 11:54:40,021 slot 7664 139953135314752 Number of Downstream_slots: 0
ERROR 2020-07-29 11:55:05,819 log_exception 7664 139949744846592 Traceback (most recent call last):
  File "/home/jerphanion/.local/share/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 241, in _serialize
    self._saveValue(group, name, slot.value)
  File "/home/jerphanion/.local/share/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 371, in _saveValue
    sg = group.create_dataset(name, data=data)
  File "/home/jerphanion/.local/share/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/jerphanion/.local/share/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1707, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

See the full trace that I get here: https://gist.github.com/jjerphan/efa46c32548cb6e58910052647baf662

#### Reproducibility

As @alyst indicated, it might really depend on a specific sequence of interactions with the UI.
In my case, I got this error when I tried to save the project after having gotten to last pane for exportation.
I have not yet been able to try to reproduce this issue without triggering this last pane

#### Screenshots
On the GUI side, the issue is reported as so like this.
![Screenshot from 2020-07-29 11-38-18](https://user-images.githubusercontent.com/13029839/88794104-d90c0f80-d195-11ea-8e23-16bd44cbe9bd.png)

#### Desktop:
    ilastik version: 1.3.3post3
    OS: Ubuntu 18.04.1
