### ISSUE TITLE
ilastik needs new version of h5py....

### ISSUE THREAD

**Issue by DerThorsten** [ilastik/ilastik#1120] opened 2015-06-18 09:47 UTC
Recent ilastik version do not open projects with an older h5py version.
T tried 2.2.x  and it did not work...(2.5 works)
The strange thing is, the error msg  seems realy not linked to hdf5....was pure luck that
I updated h5py to see if this will fix the error.

The error is something like `__init__` takes at most 6 args,  7 are given...

I guess the hdf5 version should be checked and a warning/error should be given

**Comment by stuarteberg** [comment] 2015-06-18 15:12
Can you paste a traceback here?  You should be able to find it in `~/.ilastik_log.txt`.

**Comment by chaubold** [comment] 2015-06-19 13:25
I remember we had that on Janez' machine, too. It does not show up in the conda build as that one has the newest h5py version, but the buildem dependency tree (and hence also the one in the 1.1.5 binary) is too old to work with the latest ilastik master. I do not recall, where in ilastik this was triggered.

**Comment by DerThorsten** [comment] 2015-06-22 12:42
i could try to reproduce the error on my machine. atm i have no access to the ~/.ilastik_log.txt.

**Comment by stuarteberg** [comment] 2015-06-29 13:14
Now that I think about it, this bug is almost certainly caused by this recent commit: f54c25b9841eb24b59848079481c43f32a7e548a.  We should probably revert that commit and try monkey-patching `threading.Thread.run()` instead.  See [this comment](https://github.com/h5py/h5py/issues/580#issuecomment-108114919) in h5py/h5py#580.

**Comment by stuarteberg** [comment] 2015-08-04 21:18
Fixed via 438708073a2598b7fb4b819d4c8e54a18fe5a441 and 23f78c621f662db9198bc5c095542e8e000294b8.  But soon that commit won't be necessary at all, once there's a new release of h5py.  See h5py/h5py#583.

**Closed by stuarteberg** 2015-08-04 21:18 UTC
Labels: easyFix, enhancement
