### ISSUE TITLE
object classification's execute key error

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1709] opened 2018-02-09 10:07 UTC
object classification execute throws a key error:

Exception(<class 'KeyError'>): KeyError(6,)

```
File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/tracking/structured/structuredTrackingGui.py", line 465, in _learn
    progressVisitor=self.progressVisitor
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/tracking/structured/opStructuredTracking.py", line 204, in _runStructuredLearning
    hypothesesGraph = self._createHypothesesGraph()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 251, in _createHypothesesGraph
    with_classifier_prior=withClassifierPrior)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 742, in _generate_traxelstore
    detProbs = self.DetectionProbabilities(time_range).wait()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/jales/software/miniconda/envs/p3-ilastik/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1195, in execute
    pool.wait()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1294, in wait
    self._clear_finishing_requests()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1390, in _clear_finishing_requests
    req.block()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in block
    self._wait(timeout) # No return value. Use wait()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 609, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/home/jales/software/miniconda/envs/p3-ilastik/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1186, in predict_forest
    prob_predictions[_t] = classifier.predict_probabilities(feats[_t].astype(numpy.float32))
```

**Comment by ilastikdev** [comment] 2018-02-09 10:25
this happens when a time frame has no objects

**Comment by ilastikdev** [comment] 2018-02-09 12:50
this is OK for an output from object count classifier
although,we might want to add info if such frames occur

so it should be up to downstream callers to deal with empty frames
and appropriate actions
I will solve this for tracking

**Comment by k-dominik** [comment] 2020-11-18 20:33
The issue is still present, closing this in favor of https://github.com/ilastik/ilastik/issues/2019

**Closed by k-dominik** 2020-11-18 20:33 UTC
Labels: bug, objectClassification
