### ISSUE TITLE
Export settings: Select directory dialog should open up in {dataset_dir}

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#1035] opened 2014-11-07 14:52 UTC
... it currently opens in $HOME on my Ubuntu.

**Comment by agarwalayush** [comment] 2015-03-26 17:38
It doesn't exactly opens in $HOME. It opens in the director from which you call the `./run_ilastik.h` .
But if you don't press `select` it saves in the `{dataset_dir}` . I am working on this issue.

**Comment by stuarteberg** [comment] 2015-03-26 19:00
Duplicate of #920

**Closed by stuarteberg** 2015-03-26 19:00 UTC
Labels: data-export
