### ISSUE TITLE
'filePath' error after saving and re-opening

### ISSUE THREAD

**Issue by PhotonPhilipp** [ilastik/ilastik#2362] opened 2020-12-03 11:18 UTC
## Describe the bug
When I save a file and try to reopen it an error report shows up. 
This happens when the raw file is saved to the lip file and also when the relative path is saved. 

## Expected behavior
opening the file again after saving it

## To Reproduce
1) create new file (carving)
2) save file
3) close file
4) open file

## Error message/traceback
![Screenshot 2020-12-03 at 12 06 07](https://user-images.githubusercontent.com/75425414/101006970-97cfa600-3561-11eb-82cd-d1d3212ae604.png)

## Desktop (please complete the following information):
 - ilastik version: 1.3.3

**Comment by k-dominik** [comment] 2020-12-04 13:01
Hi @PhotonPhilipp ,

thank you for reporting this. I have problems reproducing this - most likely I'm not trying it with the right version of ilastik and operating system.

So could I ask you whether you are on Windows, MacOSX, or Linux? Also which version are you using exactly? `1.3.3post3`?
What is the type of file you are adding?

Hope we can resolve this quickly
Cheers
Dominik

**Comment by PhotonPhilipp** [comment] 2020-12-04 13:16
Hi, thanks for the fast response! So it is a bit complicated:
The version 1.3.3post3 is on our (Windows) workstation, which I am connected to remotely with my Mac. 
However, the files are never saved on my Mac but on a file server. To make it more complicated, I was not always connected to the same workstation, meaning the program was running on different workstations (not at the same time). but the file was always saved on the same server. 

And, the workstation I am testing now has version 1.3.3pot3, but it might be that another workstation has 1.3.3post1, would that be an issue?

cheers,
Philipp

**Comment by k-dominik** [comment] 2020-12-04 14:52
Hi @PhotonPhilipp ,

sometimes minor version changes do fix things... So I thought I could maybe reproduce it with the right version. But I tried to create one in `1.3.3post1`, one with `1.3.3post3` and open it with both and could not reproduce the issue. Maybe it's somehow related to the whole setup. Could you do us a favor and send us the log? Ideally you'd remove the log first, reproduce the issue, and then send us the log to either team@ilastik.org or post it here.

On windows you can find the log at `C:\Users\<yourUserName>\ilastik_log.txt`.

**Comment by Tomaz-Vieira** [comment] 2020-12-04 16:45
Fixed in  https://github.com/ilastik/ilastik/pull/2241, available in the beta release

**Closed** 2020-12-04 16:45 UTC
