### ISSUE TITLE
pixel classification / auto-context: feature selection applets look different, on OSX

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1550] opened 2017-06-21 08:26 UTC
In pixel classification as well as in auto-context the feature selection applet is used providing the same functionality. On OSX, however, these applets don't look the same.

**Comment by chaubold** [comment] 2017-06-21 08:34
Looks the same for me (latest dev environment). I remember @stuarteberg and me investigating this weird scaling of the feature selection matrix, and it looked like it's due to the MacBook's high DPI retina displays that Qt4 doesn't like. IIRC switching to Qt5 will fix that problem.

Closing for now unless we can reproduce it.

**Closed by chaubold** 2017-06-21 08:34 UTC
