### ISSUE TITLE
counting workflow frequently crashes on Windows

### ISSUE THREAD

**Issue by ukoethe** [ilastik/ilastik#1166] opened 2015-12-04 19:40 UTC
here is the error log:
```
INFO 2015-12-03 11:14:15,732 ilastik_main 93652 72176 Starting ilastik from "C:\conda\envs\ilastik".
INFO 2015-12-03 11:14:16,328 opThresholdTwoLevels 93652 72176 Using 'vigra' labeling implemetation
ERROR 2015-12-03 11:15:28,323 countingOperators 93652 71424 ERROR: could not learn regressor
ERROR 2015-12-03 11:15:28,325 countingOperators 93652 71424 fullFeatMatrix shape = (497L, 49L), dtype = float64
ERROR 2015-12-03 11:15:28,325 countingOperators 93652 71424 fullLabelsMatrix shape = (497L,), dtype = float64
ERROR 2015-12-03 11:15:28,476 excepthooks 93652 78528 Unhandled exception in thread: 'TileProvider-78528'
ERROR 2015-12-03 11:15:28,494 excepthooks 93652 74008 Unhandled exception in thread: 'TileProvider-74008'
ERROR 2015-12-03 11:15:28,502 excepthooks 93652 78528 Traceback (most recent call last):
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\tiling.py", line 90, in _render
    img = self.image_req.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 387, in wait
    return self.toImage()
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 393, in toImage
    self._arrayreq.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 471, in wait
    rawData = self._rawRequest.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "C:\conda\envs\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 229, in wait
    a = self._req.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 128, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\conda\envs\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\opCounting.py", line 152, in execute
    data = self.inputs["Input"][key].wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 355, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 469, in _executeOutput
    dirtyPool.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1141, in wait
    self.submit()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1180, in submit
    self._clear_finishing_requests()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\conda\envs\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 385, in execute
    forests=self.inputs["Classifier"][:].wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 292, in execute
    value = request.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\conda\envs\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 305, in execute
    pool.wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1148, in wait
    self._clear_finishing_requests()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\conda\envs\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\conda\envs\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 301, in train_and_store
    = self.numRegressors, trainAll = False)
  File "C:\conda\envs\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingsvr.py", line 563, in fitPrepared
    regressor = self._fit(img[indices, :], dot[indices], newTags, newBoxConstraints)
  File "C:\conda\envs\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingsvr.py", line 587, in _fit
    regressor.fit(img, dot)
  File "C:\conda\envs\ilastik\lib\site-packages\sklearn\ensemble\forest.py", line 260, in fit
    tree = self._make_estimator(append=False)
  File "C:\conda\envs\ilastik\lib\site-packages\sklearn\ensemble\base.py", line 76, in _make_estimator
    estimator = clone(self.base_estimator_)
  File "C:\conda\envs\ilastik\lib\site-packages\sklearn\base.py", line 45, in clone
    new_object_params = estimator.get_params(deep=False)
  File "C:\conda\envs\ilastik\lib\site-packages\sklearn\base.py", line 217, in get_params
    warnings.filters.pop(0)
IndexError: pop from empty list
```

**Comment by stuarteberg** [comment] 2015-12-04 19:47
This is a duplicate of #1149.

**Closed by stuarteberg** 2015-12-04 19:47 UTC
Labels: bug
