### ISSUE TITLE
error using multicut workflow

### ISSUE THREAD

**Issue by Histo23** [ilastik/ilastik#1579] opened 2017-08-24 08:46 UTC
Hi,
Using the multicut workflow (ilastik 1.2.2rc4 on windows 7) I always get following error message:
"too many values to unpack" after pressing the "update watershed" button. 
I'm working on image volumes (512x512x142). The funny thing is that it had worked ones at the beginning but since then I always get this error. I also tried different parameters in the DT watershed setup menu but always get the same error.

**Comment by chaubold** [comment] 2017-08-24 11:43
@FynnBe, didn't we see the same behaviour on your machine? IIRC the problem is that we ship the wrong version of our watershed library in Windows, so the ilastik code is expecting more return values than the watershed library provides... 

I know we fixed the error with @FynnBe in his development environment, but I'm not sure (I'm not a windows user) how we can fix that in the binary...

**Comment by Histo23** [comment] 2017-08-24 14:52
So that means at the moment this workflow can't be used in windows? That's a pity. It looked very promising.

**Comment by chaubold** [comment] 2017-08-24 15:53
Okay I talked to @FynnBe and we think you do not need any new version of the watershed library, but you should be able to fix this by editing the `opWsdt.py` file in your ilastik installation in `ilastik-meta/ilastik/applets/wsdt` and change line 67 as follows:

```diff
--- a/ilastik/applets/wsdt/opWsdt.py
+++ b/ilastik/applets/wsdt/opWsdt.py
@@ -64,7 +64,7 @@ class OpWsdt(Operator):
 
         if self.debug_results:
             self.debug_results.clear()
-        ws, max_label = wsDtSegmentation( pmap[...,0],
+        ws = wsDtSegmentation( pmap[...,0],
                                           self.Pmin.value,
                                           self.MinMembraneSize.value,
                                           self.MinSegmentSize.value,
```

Please let us know whether that helps.

**Comment by Histo23** [comment] 2017-08-28 09:05
It works now! Thanks for the help.

**Comment by chaubold** [comment] 2017-11-20 15:09
Should also be fixed in the latest beta release

**Closed by chaubold** 2017-11-20 15:09 UTC
