### ISSUE TITLE
Errow when loading a new Manual Tracking project

### ISSUE THREAD

**Issue by gcharvin** [ilastik/ilastik#1197] opened 2016-03-16 15:51 UTC
Hi, 
i get this message when I attempt to create a new Manual Tracking project with Ilastik 1.1.8 : 

```
Could not load project file.
Could not create instance of '<class 'ilastik.workflows.tracking.manual.manualTrackingWorkflow.ManualTrackingWorkflow'>'
args   = (<ilastik.shell.gui.ilastikShell.IlastikShell object at 0x11021f478>, False, [], [])
kwargs = {}
The exception was:
local variable 'default_export_filename' referenced before assignment
Traceback:
Traceback (most recent call last):
  File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operator.py", line 107, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/tracking/manual/manualTrackingWorkflow.py", line 69, in __init__
    self.dataExportApplet = TrackingBaseDataExportApplet(self, "Tracking Result Export")
  File "/Applications/ilastik-1.1.8-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportApplet.py", line 35, in __init__
    self._default_export_filename = default_export_filename
UnboundLocalError: local variable 'default_export_filename' referenced before assignment
```

Best, 
Gilles

**Comment by stuarteberg** [comment] 2016-03-16 17:07
Duplicate of #1169. This will be fixed when we release 1.1.9 in the coming days.

**Closed by stuarteberg** 2016-03-16 17:07 UTC
