### ISSUE TITLE
Can't open folder of 8-bit tifs

### ISSUE THREAD

**Issue by colemanbroad** [ilastik/ilastik#1487] opened 2017-05-05 09:21 UTC
Get an error when trying to import a 3D tiff file in ilastik 1.2.1

`type object 'AxisInfo' has no attribute 'q'`

It was saved as uint8s.

**Comment by k-dominik** [comment] 2017-05-05 09:35
Hi @colemanbroad, 

could maybe add a few more details about the issue? I assume you are on linux or osx?! And could you please attach the error log?

Cheers

**Comment by colemanbroad** [comment] 2017-05-05 09:40
Yes, I’m on OSX 10.11.6.

Where can I find the error log? I can't find it in any of the drop down menus.

When I try to import a single file:

![screen shot 2017-05-05 at 11 38 26](https://cloud.githubusercontent.com/assets/2424664/25740623/95362522-3187-11e7-8d1c-14949f4bc80d.png)

When I try to import a directory:

![screen shot 2017-05-05 at 11 38 42](https://cloud.githubusercontent.com/assets/2424664/25740631/a0fe3d04-3187-11e7-8cc4-7e760828853d.png)

best,
Coleman

**Comment by k-dominik** [comment] 2017-05-05 12:45
thank you for also trying a single file.

The log is usually located in the home folder. The file is called `ilastik_log.txt`. Since you're on the mac, you can probably just locate it in Finder under "All My Files"?

**Comment by colemanbroad** [comment] 2017-05-05 12:55
OK, here's the log...

[ilastik_log.txt](https://github.com/ilastik/ilastik/files/979052/ilastik_log.txt)

**Comment by k-dominik** [comment] 2017-05-05 13:19
So, it seems that one of the axes is labeled `q` in your file. We currently expect the axes labels to be one of `t - time`, `c - color` and the spatial axes `x`, `y`, and `z`. Is it possible that one of the image axes in the tiff file is labeled `q` ? How did you generate the image?

**Comment by colemanbroad** [comment] 2017-05-05 13:20
hmmm… I saved a numpy array to a tif file using scikit-image.io <http://scikit-image.io/>

**Comment by k-dominik** [comment] 2017-05-05 13:57
I haven't worked with skimage before, but both images created with the following example work for me:

```
import skimage.io
import numpy

data = numpy.random.randint(0, 255, (100, 100, 3)).astype(numpy.uint8)
# save colored 2d image
skimage.io.imsave('testdata.tiff', data)
# save greyscale 2d image
skimage.io.imsave('testdata.tiff', data[..., 0])

```

i might need additional information to reproduce the problem. Is there any chance you could share some example data?

**Comment by colemanbroad** [comment] 2017-05-05 14:02
Yes, these 2d images work for me as well. But when I modify this example to create 3d images it fails with the same error. Maybe skimage.io <http://skimage.io/> (really calls down to tifffile.py) saves 3d images with different metadata?

thanks!
Coleman

**Comment by k-dominik** [comment] 2017-05-05 14:12
Ok, I can reproduce the error now and investigate how to fix it

**Comment by colemanbroad** [comment] 2017-05-05 14:18
So, I can get around this issue if I first open the file with Fiji, then re-save it. There is lots of additional metadata in the Fiji-saved version:

ImageDescription: SCIFIO=0.31.1
axes=X,Y,Z
lengths=532,1352,108
scales=1.0,1.0,1.0
units=pixel,pixel,pixel
bitsPerPixel=16
images=108
channels=1
slices=108
frames=1
hyperstack=true
mode=composite
unit=pixel

Software: SCIFIO

**Comment by k-dominik** [comment] 2017-05-05 14:42
yep, that looks better. So it seems that the version of tifffile included in ilastik is a bit outdated. In principle you should get around all that by saving the file in the following way using a recent tifffile/scikit-image version:
```python
skimage.io.imsave('myfile.tiff', data, 'tifffile', metadata={axes: "ZYXC"})
```

**Comment by k-dominik** [comment] 2017-05-05 14:56
@akreshuk @stuarteberg there might be tiff-files without proper axis metadata. `tifffile`, at least, generates a `Q` (unknown) axis-tag in such cases. Should we assume default order and open the files, giving the user the chance to correct the order via the usual route? Or just not support those cases and generate a proper error message for that?

**Comment by akreshuk** [comment] 2017-05-05 14:58
I like the default order and let them correct it idea. There is some other problem with the newer version of tifffile, we had this before. Something with multi-page tiffs I believe.

**Comment by akreshuk** [comment] 2017-05-12 12:24
@k-dominik , should we close this one?

**Comment by k-dominik** [comment] 2017-05-12 12:34
yah, the merge of https://github.com/ilastik/lazyflow/issues/238 fixes it

**Closed by k-dominik** 2017-05-12 12:34 UTC
