### ISSUE TITLE
starting ilastik in headless mode shows a system error message box: cplex1251.dll and gurobi55.dll not found

### ISSUE THREAD

**Issue by dagophil** [ilastik/ilastik#1121] opened 2015-06-20 14:24 UTC
I use windows and do not have cplex or gurobi installed. When I start ilastik in headless mode using
`ilastik.exe --headless --project C:\MyProject.ilp --retrain`,
two message boxes show up: _cplex1251.dll not found_ and _gurobi55.dll not found_.
When I close the message boxes, ilastik retrains the project as if there was no error.

![gurobi_not_found](https://cloud.githubusercontent.com/assets/6207208/8267521/4b6a6766-1765-11e5-9fe5-776a1a47c71e.png)

I tracked the problem down to the file
`ilastik-1.1.5\ilastik\ilastik\ilastik\applets\counting\cwrapper\gurobi\__init__.py`
In line 38, the command `extlib = ctypes.cdll.LoadLibrary(dllfile)` checks if the file
`ilastik-1.1.5\ilastik\ilastik\ilastik\applets\counting\cwrapper\gurobi\gurobiwrapper.dll`
can be loaded. This dll file exists, but trying to load it shows the message box from above.

The problem can be solved by removing or renaming gurobiwrapper.dll (and cplex dll).

_Additional information:_
(1) I use a script to retrain several ilastik projects after another. Since it is necessary to click away the message boxes, the script does not run automatically.
(2) I think the dll errors occur in the gui mode as well, but Qt suppresses the message boxes.

**Comment by chaubold** [comment] 2015-06-23 12:08
This is not related to tracking but counting. @ukoethe probably knows most about that?

On my Mac build, I tried to reproduce this problem but it works fine (probably because I did not pay attention to build the counting CPLEX/Gurobi wrappers properly). It does notice that no cplex is available and thus complains about the missing automated tracking, though. Tag 1.1.5 checked out for `ilastik-meta`:

```
python ilastik.py --headless --project /Users/chaubold/Untitled.ilp --retrain
WARNING __init__.py(14): UserWarning: Couldn't import IIBoost classifier.
WARNING lil.py(21): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING lil.py(21): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING __init__.py(148): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING __init__.py(148): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING _validation.py(5): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING _validation.py(5): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING __init__.py(546): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING __init__.py(546): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING _continuous_distns.py(24): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING _continuous_distns.py(24): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING stats.py(188): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING stats.py(188): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING interpolate.py(28): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING interpolate.py(28): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
WARNING __init__.py(90): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
WARNING __init__.py(90): RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility
INFO ilastik_main: Starting ilastik from "/Users/chaubold/hci/code/ilastik/src".
Starting ilastik from "/Users/chaubold/hci/code/ilastik/src".
INFO ilastik.applets.thresholdTwoLevels.opThresholdTwoLevels: Using 'vigra' labeling implemetation
WARNING 2015-06-23 14:05:31,592 __init__ 41991 140735269540624 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: dlopen(/Users/chaubold/hci/code/ilastik/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgmlink.so, 2): Library not loaded: /Users/chaubold/hci/code/ilastik/lib/libilocplex.dylib
  Referenced from: /Users/chaubold/hci/code/ilastik/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgmlink.so
  Reason: image not found
INFO ilastik.shell.projectManager: Opening Project: /Users/chaubold/Untitled.ilp
WARNING appletSerializer.py(330): UserWarning: Deserialization: Could not locate value for slot 'RegionStart'.  Skipping.
WARNING appletSerializer.py(330): UserWarning: Deserialization: Could not locate value for slot 'RegionStop'.  Skipping.
DEBUG lazyflow.operators.classifierOperators: Training new classifier: Parallel Vigra Random Forest Factory (100 trees total)
INFO lazyflow.classifiers.parallelVigraRfLazyflowClassifier: Training complete. Average OOB: 0.0
```

**Comment by stuarteberg** [comment] 2015-06-26 17:16
Another user reported having this same problem today.  @ukoethe, @ilastikdev do you have any ideas?

**Comment by ukoethe** [comment] 2015-06-30 16:14
This is only a warning that occurs when ilastik tries to open `gurobiwrapper.dll` within a try/except block. Unfortunately, on Windows the OS interferes and notifies the user that a dependency of `gurobiwrapper.dll` wasn't found. When one simply presses "OK", ilastik continues without the gurobi-variant of the counting workflow as desired. Of course, it is annoying to have the user press a button in headless mode.

In GUI mode, Qt apparently manages to supress the warning, but I don't know how they do it (`cdll.LoadLibrary()`has no options). Removing/renaming `gurobiwrapper.dll` would also solve the problem, but would make it more difficult for the user to recover the counting workflow by installing gurobi. 

Another easy fix is to add in `counting\cwrapper\gurobi\__init__.py`just before line 38:
```python
    ctypes.cdll.LoadLibrary("gurobi55.dll")
```
The downside is that we must not forget to update the version number here whenever we update the Gurobi version in the build scripts.

The mercedes solution is a tool called "pefile" (https://github.com/erocarrera/pefile) which can portably ask a shared library for its dependencies, resulting in code like this:
```python
import pefile
pe =  pefile.PE(dllfile)
gurobi = reduce(lambda x,y: y.dll if y.dll.count("gurobi") else x, 
                            pe.DIRECTORY_ENTRY_IMPORT, "")  # returns "gurobi55.dll"
ctypes.cdll.LoadLibrary(gurobi)
```
This may also be interesting for other workflows that need to handle optional dependencies. Perhaps this can be achieved in an even simpler way, without adding a new ilastik dependency?

**Comment by k-dominik** [comment] 2023-03-27 13:12
this hasn't been reported in the past 5 years at least. Closing this. Please open a new issue if you're running into this with versions `1.4.0` and greater.

**Closed by k-dominik** 2023-03-27 13:12 UTC
Labels: densityCounting
