### ISSUE TITLE
Save should retain directory of last call? (feature request)

### ISSUE THREAD

**Issue by hugadams** [ilastik/ilastik#958] opened 2014-07-13 23:57 UTC
I noticed that when we save a layer of an image to disk and then go to save something else, the last used directory isn't retained.  When I say save, I believe I mean "export", which we access at the bottom of the interface as an icon (can post screenshot if this is unclear).

I think this would go a long way for convenience sake.  For example, we often want to save the binary image, uint-labeled image etc... as we go, for several images.

---

Edit from @stuarteberg: Related to #920, but slightly different. In this case, the user is referring to the "Export Layer" feature, not the export applet.

**Comment by stuarteberg** [comment] 2017-03-01 02:43
Duplicate of #1060. Fixed via ilastik/volumina@2ebbfb42b62e3997d919ab84f65077e7f34e59dc

**Closed by stuarteberg** 2017-03-01 02:43 UTC
Labels: data-export, user-request
