### ISSUE TITLE
Export as multipage tiff does not export all slices

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1534] opened 2017-06-01 11:45 UTC
For me it export the first 10 and the rest is black.

**Comment by emilmelnikov** [comment] 2019-02-13 16:32
Closing this issue: cannot reproduce the error.

Steps to reproduce:
1. Crop [MC0509C3X100-2.tif](http://data.ilastik.org/pixel-classification/3d/MC0509C3X100-2.tif) to 200x600 with ilastik data export, leaving all 103 time slices and all 3 channels.
1. Using the previous file as a source, train pixel classification on some labels, added to multiple time slices
1. Export probabilities as multipage tiff, converting values to uint8 and normalizing to [0; 255].

System information:
- Ubuntu 18.04
- ilastik ilastik/ilastik@c0ea78740b3a697638133be06a92dbc5adc0ee58
- lazyflow ilastik/lazyflow@7a06c4d34b831bea9284aab473fd3f8de95d009a
- volumina ilastik/volumina@c500bc07f9dde45aad2d54464738e5af1cbfa776

**Comment by akreshuk** [comment] 2019-02-13 20:42
Wait, wait, that might not be all! In ilastik time and depth of a stack are handled very differently. So you have to test on a stack which has multiple z slices, not multiple time slices. You can re-use the file you had, but change the axes assignment to "z" from "t" in the input data applet.

**Comment by emilmelnikov** [comment] 2019-02-14 09:21
I've tried to do the same with the Z axis instead of T: everything still works.

Currently, `opExportMultipageTiff` from lazyflow treats all dimensions except Y and X just as page sources, so if error is in the export alone, it shouldn't make a difference.

**Comment by k-dominik** [comment] 2023-10-18 15:01
i've tried with `1.4.1b7`, multipage tiff, 3D 256**3 - could not reproduce this issue. If someone else runs into this, please open a new issue!

**Closed by k-dominik** 2023-10-18 15:01 UTC
Labels: bug
