### ISSUE TITLE
Importing labels broken in pixel classification

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1819] opened 2018-08-23 21:50 UTC
In the current master, if one exports the labels layer to h5 first and then imports it again in a new project, the following error comes up:

```pytb
ERROR 2018-08-23 23:47:15,539 excepthooks 2114 139944330757888 Traceback (most recent call last):
  File "/home/anna/miniconda3/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/labeling/labelingImport.py", line 165, in import_labeling_layer labelingSlots.labelInput, labelInfo )
  File "/home/anna/miniconda3/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/labeling/labelingImport.py", line 269, in __init__
    self._initMetaInfoWidgets()
  File "/home/anna/miniconda3/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/labeling/labelingImport.py", line 390, in _initMetaInfoWidgets
    self.inputMetaInfoWidget.initSlot( dataInputSlot )
  File "/home/anna/miniconda3/envs/ilastik-devel/ilastik-meta/volumina/volumina/widgets/slotMetaInfoDisplayWidget.py", line 44, in initSlot
    self._refresh()
  File "/home/anna/miniconda3/envs/ilastik-devel/ilastik-meta/volumina/volumina/widgets/slotMetaInfoDisplayWidget.py", line 48, in _refresh
    shape = tuple( self._slot.meta.original_shape )
TypeError: 'NoneType' object is not iterable
```

**Comment by emilmelnikov** [comment] 2019-09-24 09:35
Cannot reproduce.

It seems that the issue has been fixed in https://github.com/ilastik/volumina/pull/235/commits/f5771cab0ebe305b1c8a7921aa4ee6d1c2f5ed08.

**Closed** 2019-09-24 11:18 UTC
Labels: pixelClassification
