### ISSUE TITLE
Multicut: TypeError: '>' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by MatthewBM** [ilastik/ilastik#1969] opened 2019-03-01 06:48 UTC
## Describe the bug
I have loaded in the example datasets for Multicut, and when running live Multicut, I get this error: TypeError: '>' not supported between instances of 'NoneType' and 'float'

I used the exact same data from the Nature SNEMI experiment. 

## Expected behavior

I want to watch Multicut run live

## To Reproduce
Load in the raw_test, raw_train, probabilities_raw.tif, probabilities_test.tif, and groundtruth.tif, and then try to run Live Multicut

## Error message/traceback
log attached
[ilastik_log.txt](https://github.com/ilastik/ilastik/files/2918223/ilastik_log.txt)

**Comment by k-dominik** [comment] 2019-03-01 07:09
Hi @MatthewBM ,

thank you for the report. This issue is already fixed in the current master, but has not been released yet (https://github.com/ilastik/ilastik/issues/1837).

As far as I remember the problem is, that no edges have been trained yet. So you can overcome this by training the edge classifier first by either
a) auto-label
b) labeling yourself

and hitting live update (the top one for the edge classifier) before you go to live-update in the multicut. In the next release this is fixed.

closing...

**Closed by k-dominik** 2019-03-01 07:09 UTC

**Comment by MatthewBM** [comment] 2019-03-01 18:25
Hi @k-dominik 

Thank you for your response.
I tried to do Auto-Label but Ilastik becomes unresponsive and has stayed that way for 12+ hours. How long is it supposed to take?
