### ISSUE TITLE
grpc._channel._InactiveRpcError on startup of Neural Network Classification (Local)

### ISSUE THREAD

**Issue by imagejan** [ilastik/ilastik#2680] opened 2023-02-22 09:40 UTC
## Describe the bug
When trying to create a new *Neural Network Classification (Local)* project (on Windows and behind a firewall/proxy), I get an error message and the stack trace pasted below.

## Expected behavior

The Neural Network Classification UI should appear.

## To Reproduce

1. Start ilastik
2. Click on *Neural Network Classification (Local)*

## Error message/traceback

```
Starting ilastik from "C:\Program Files\ilastik-1.4.0-gpu\lib".
31648
site.config.json: 5.71kiB [00:00, ?iB/s]
C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:471: UserWarning: Download (5705) does not have expected size (2006).
  warnings.warn(f"Download ({t.n}) does not have expected size ({total_size}).")
collection.json: 186kiB [00:00, ?iB/s]
C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:471: UserWarning: Download (186338) does not have expected size (23910).
  warnings.warn(f"Download ({t.n}) does not have expected size ({total_size}).")

CUDA version: 11.3

Available devices:
  * cpu
  * cuda:0

Starting server on 127.0.0.1:57389
Writing connection data to C:\Users\eglijan\AppData\Local\Temp\tiktorch_connectiono6ts_6nr\conn.json
ERROR 2023-02-22 10:30:54,821 log_exception 29672 30396 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operator.py", line 117, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_localWorkflow.py", line 53, in __init__
    super().__init__(shell, headless, workflow_cmdline_args, project_creation_args, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_nnWorkflowBase.py", line 91, in __init__
    self._createClassifierApplet(headless=self._headless, conn_str=connection_string)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_localWorkflow.py", line 67, in _createClassifierApplet
    preferred_cuda_device_id, device_name = super()._configure_device(conn)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_nnWorkflowBase.py", line 245, in _configure_device
    devices = conn.get_devices()
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operators\tiktorch\classifier.py", line 355, in get_devices
    resp = self._client.ListDevices(inference_pb2.Empty())
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1677058254.822000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1677058254.822000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\shell\gui\ilastikShell.py", line 1628, in _loadProject
    project_creation_args=project_creation_args,
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\shell\projectManager.py", line 240, in __init__
    self.workflow = workflowClass(shell, headless, self._workflow_cmdline_args, self._project_creation_args)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operator.py", line 139, in __call__
    raise RuntimeError(err)
RuntimeError: Could not create instance of '<class 'ilastik.workflows.neuralNetwork._localWorkflow.LocalWorkflow'>'
args   = (<ilastik.shell.gui.ilastikShell.IlastikShell object at 0x00000151847B9B88>, False, [], [])
kwargs = {}
The exception was:
<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1677058254.822000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1677058254.822000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>
Traceback:
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operator.py", line 117, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_localWorkflow.py", line 53, in __init__
    super().__init__(shell, headless, workflow_cmdline_args, project_creation_args, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_nnWorkflowBase.py", line 91, in __init__
    self._createClassifierApplet(headless=self._headless, conn_str=connection_string)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_localWorkflow.py", line 67, in _createClassifierApplet
    preferred_cuda_device_id, device_name = super()._configure_device(conn)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_nnWorkflowBase.py", line 245, in _configure_device
    devices = conn.get_devices()
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operators\tiktorch\classifier.py", line 355, in get_devices
    resp = self._client.ListDevices(inference_pb2.Empty())
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1677058254.822000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1677058254.822000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>


ERROR 2023-02-22 10:30:54,837 log_exception 29672 30396 Could not load project file.
Could not create instance of '<class 'ilastik.workflows.neuralNetwork._localWorkflow.LocalWorkflow'>'
args   = (<ilastik.shell.gui.ilastikShell.IlastikShell object at 0x00000151847B9B88>, False, [], [])
kwargs = {}
The exception was:
<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1677058254.822000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1677058254.822000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>
Traceback:
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operator.py", line 117, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_localWorkflow.py", line 53, in __init__
    super().__init__(shell, headless, workflow_cmdline_args, project_creation_args, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_nnWorkflowBase.py", line 91, in __init__
    self._createClassifierApplet(headless=self._headless, conn_str=connection_string)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_localWorkflow.py", line 67, in _createClassifierApplet
    preferred_cuda_device_id, device_name = super()._configure_device(conn)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\ilastik\workflows\neuralNetwork\_nnWorkflowBase.py", line 245, in _configure_device
    devices = conn.get_devices()
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\lazyflow\operators\tiktorch\classifier.py", line 355, in get_devices
    resp = self._client.ListDevices(inference_pb2.Empty())
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Program Files\ilastik-1.4.0-gpu\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1677058254.822000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1677058254.822000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>
```

## Screenshots

![image](https://user-images.githubusercontent.com/2033938/220580763-66d45582-4531-4dee-9bc7-23e999ff49e6.png)

## Desktop (please complete the following information):
 - ilastik version: 1.4.0-gpu
 - OS: Windows 10

**Comment by k-dominik** [comment] 2023-02-22 10:02
Hi @imagejan,

sorry you ran into this. What's happening is that we're starting our little tiktorch server inside ilastik, and on the first go it takes too long on some machines. Trying again should fix this. The error message is horrendous though - sorry :/

Cheers
Dominik

**Comment by imagejan** [comment] 2023-02-22 19:24
Thanks @k-dominik for the quick reply.

I tried several times repeating the project creation, or loading the initialized MyProject.ilp file directly, but both reproducibly lead to the above error.

**Comment by k-dominik** [comment] 2023-02-23 07:09
Hello @imagejan, thank you for the update?

Would you be comfortable changing one file in your ilastik installation? It would be great to find out what time is needed 
"in the field" for the first startup (if it is indeed that issue)?

If yes, could you change the `max_wait` to something larger than `20`...:
https://github.com/ilastik/ilastik/blob/e093db405cda4a4eeb529aebebbc6f55f339a5a5/ilastik/workflows/neuralNetwork/_localLauncher.py#L74
(it should be in `C:\Program Files\ilastik-1.4.0\Lib\site-packages\ilastik\workflows\neuralNetwork\_localLauncher.py`)
? We can then change the default on our side...

**Comment by imagejan** [comment] 2023-10-09 08:05
(probably duplicate of #2722 ?)

**Comment by btbest** [comment] 2023-10-09 09:34
@imagejan Can you confirm if the problem is also due to VPN and/or proxy in your environment? If that's the case, I would close this one in favour of the other #2722 since we already have a couple of comments with possible root causes / fixes there.

**Comment by imagejan** [comment] 2023-10-09 13:46
@btbest thanks for following up. As I wrote in the first post above, we are behind a firewall/proxy, yes. But I currently don't have a chance to test *without* a proxy.

Nevertheless, feel free to close this in favor of #2722.

**Closed** 2023-10-11 13:13 UTC
