### ISSUE TITLE
--table_filename flag raises exception when exporting h5

### ISSUE THREAD

**Issue by markemus** [ilastik/ilastik#1622] opened 2017-10-23 17:21 UTC
I'm running a headless object classification project and trying to export the feature table. We need the h5 feature table because it includes the separated object images inside it, so csv is not an option. 

If I configure the feature table to export as csv it works fine even in headless mode. 

But when it's configured to export as h5, although it works fine in the gui, running the project headless gives the following error:

`Exception: (Exception("Developer error: When ilastik is running in headless mode, you aren't allowed to import PyQt4.",), <built-in function _unpickle_enum>, ('PyQt4.QtCore', 'CheckState', 0))`

**Comment by k-dominik** [comment] 2017-10-23 18:55
Hi markemus, really unfortunate that you experiencing a problem. Could I ask which version of ilastik it is that you are running and on which platform you are?

**Comment by markemus** [comment] 2017-10-23 18:57
Hello again k-dominik. I'm running ilastik 1.2.2 on Ubuntu 16.04.3 LTS.

**Comment by k-dominik** [comment] 2017-10-23 18:58
All right, thank you. I'll look into it tomorrow!

**Comment by markemus** [comment] 2017-10-23 19:00
Thank you :)

**Comment by k-dominik** [comment] 2017-10-24 14:54
So yeah, I can definitely reproduce it with your description, so thanks a lot - now let's see about a fix...

**Comment by k-dominik** [comment] 2017-10-24 16:07
Hey, just dumping some notes, mainly for myself, here:

The `h5` table export settings are saved in the `.ilp` file via pickle. One of the values there, for the key `'include raw'` is pickled as a  `PyQt4.QtCore.CheckState` object. When unpickling, of course, `PyQt4` is imported and that whole business is causing the exception (because we don't allow importing Qt in headless mode).

**Comment by k-dominik** [comment] 2017-10-24 16:23
Hi @markemus , right now I could supply you with a one line Hack.
You would have to add the following to `.../your_ilastik_install/ilastik-meta/ilastik/ilastik/widgets/exportObjectInfoDialog.py` : 

line 132 in this file should be:
```python 
                "include raw": self.ui.includeRaw.checkState(),
```

change that line to
```python
                "include raw": str(self.ui.includeRaw.checkState()),
```

Then you have to restart ilastik, reopen your project, configure `.h5` table export, run the export once, just to be sure and then save the project.
I think that should resolve your problem

**Comment by markemus** [comment] 2017-10-25 13:58
It works! Thank you so much. The h5 feature table now exports perfectly from headless.

**Comment by k-dominik** [comment] 2017-10-25 14:13
cool!

**Comment by k-dominik** [comment] 2017-10-25 14:13
i'll leave this issue open, until we have fixed it on our master :)

**Comment by akreshuk** [comment] 2018-04-19 05:52
Is that one fixed now that we are all Python 3 and Qt5?

**Comment by k-dominik** [comment] 2018-08-13 09:17
investigating this right now - found that it doesn't raise an exception in headless mode, despite importing `PyQt5` on unpickling: #1812 ... investigating this

**Closed** 2018-08-14 10:37 UTC
Labels: bug, objectClassification
