### ISSUE TITLE
Conservation Tracking results are not identical

### ISSUE THREAD

**Issue by Steffen-Wolf** [ilastik/ilastik#1232] opened 2016-06-20 10:57 UTC
I have compared the results from conservation tracking(CT) from  (#1186) with the current binary  (ilastik 1.1.9). The results are not identical.

On the drosophila dataset CT produces 2025 appearances ( the binary produced 90) and  2238 disappearances (the binary produced 303) with all parameters being equal. All other evaluation measures (number of divisions and moves) are approximately equal.

I suspect that the dis/appearance cost parameters are treated differently in both versions during graph construction.

**Comment by chaubold** [comment] 2016-06-27 14:00
@ilastikdev and I have just tried to reproduce the error (this time on the Mitocheck example dataset from the website). We get the following numbers (disabled merger resolving and divisions, exported the results as H5 sequence, and ran the comparison script from https://github.com/chaubold/hytra/blob/development/scripts/compare_tracking.py), where base=learning-branch and contestant=ilastik 1.1.9 binary:

```
Measuring performance...
-> Precision: 0.999
-> Recall: 0.873
-> F-measure 0.931:
Check 0.931361163743

[overall]
n_base = 8731
n_contestant = 7630
precision = 0.9986
recall = 0.8726
f_measure = 0.9314:

[move]
n_base = 6688
n_contestant = 6694
precision = 0.9988
recall = 0.9997
f_measure = 0.9993

[merger]
n_base = 870
n_contestant = 870
precision = 1.0000
recall = 1.0000
f_measure = 1.0000

[appearance]
n_base = 637
n_contestant = 62
precision = 0.9677
recall = 0.0942
f_measure = 0.1717

[disappearance]
n_base = 536
n_contestant = 4
precision = 0.7500
recall = 0.0056
f_measure = 0.0111
```

While the number of appearances and disappearances has a large deviation, the mergers and transitions(=moves) look close enough to resemble the same tracking solution. @ilastikdev will validate that with divisions turned on because then it will be easier to relate the appearance/disappearance numbers with what we actually see in the data.

I've also compared the two by converting the results to the Cell Tracking Challenge format and using their comparison measure, and there we get `0.998788`.

We came to the conclusion that this must be related to the way appearance and disappearance events are extracted (in pgmlink!). We did touch this part between the binary and the current version - to some part this was also due to problems in MergerResolution. So it might be these numbers are misleading because the tracking result is actually the same, just not the same amount of appearance/disappearance events gets exported.

As far as I can tell there are no users apart from us who use the `event`-style export, so we could:

1. ignore the change and hope nobody notices. (We won't be affected either because in all other scripts we simply deduce appearances/disappearances from the presence/lack of moves that connect detections).
2. try to go back to the old format, possibly breaking merger resolving, which would require additional testing/debugging/(making sure other scripts still work)

**Comment by ilastikdev** [comment] 2016-06-28 11:49
I have checked the solutions with division classifier trained on the mitocheck data. The increase in the number of (dis)appearance objects is due to the code assigning objects that are misdetections in the tracking solution of the binary release code .

Events method has been modified to assure consistent behavior of conservation tracking.

**Comment by ilastikdev** [comment] 2016-06-28 11:53
Segmentation is the same in both cases, so are the training labels, but due to the randomness of RF we get slightly different results.


Measuring performance...
-> Precision: 0.989
-> Recall: 0.989
-> F-measure 0.989: 
Check 0.988996763754

[overall]
n_base = 6953
n_contestant = 6952
precision = 0.9891
recall = 0.9889
f_measure = 0.9890:

[move]
n_base = 6727
n_contestant = 6747
precision = 0.9910
recall = 0.9939
f_measure = 0.9924

[merger]
n_base = 74
n_contestant = 53
precision = 1.0000
recall = 0.7162
f_measure = 0.8346

[multiFrameMove]
n_base = 0
n_contestant = 0
precision = nan
recall = nan
f_measure = nan

[division]
n_base = 128
n_contestant = 131
precision = 0.9237
recall = 0.9453
f_measure = 0.9344

[appearance]
n_base = 15
n_contestant = 13
precision = 0.8462
recall = 0.7333
f_measure = 0.7857

[disappearance]
n_base = 9
n_contestant = 8
precision = 0.6250
recall = 0.5556
f_measure = 0.5882

[overall|visibility]
n_base = 6953
n_contestant = 6952
precision = 0.9891
recall = 0.9889
f_measure = 0.9890

[move|visibility]
n_base = 6727
n_contestant = 6747
precision = 0.9910
recall = 0.9939
f_measure = 0.9924

[division|visibility]
n_base = 128
n_contestant = 131
precision = 0.9237
recall = 0.9453
f_measure = 0.9344

[appearance|visibility]
n_base = 15
n_contestant = 13
precision = 0.8462
recall = 0.7333
f_measure = 0.7857

[disappearance|visibility]
n_base = 9
n_contestant = 8
precision = 0.6250
recall = 0.5556
f_measure = 0.5882

**Closed** 2016-06-28 12:01 UTC
Labels: bug, showstopper, tracking
