### ISSUE TITLE
How to troubleshoot a run_ilastik.sh: line 77: 85017 Segmentation fault  (v1.3.3)

### ISSUE THREAD

**Issue by raymond301** [ilastik/ilastik#2252] opened 2020-06-11 21:41 UTC
## Describe the bug
I have a trained model in Pixel Classification, and when I want to apply to Batch Processing, I get a segmentation fault.
It's not consistent though. I have other models, when I try the exact same large TIFF in other projects it does work. So I suspect it's a memory configuration issue.

## Expected behavior
I expect to either receive a descriptive error or for the image to generate a probability matrix. In batch processing 

## Error message/traceback

```pytb
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
Warning: TIFFDecoder: no TIFFTAG_SAMPLEFORMAT or TIFFTAG_DATATYPE, guessing pixeltype 'UINT16'.
Fatal Python error: Segmentation fault

Thread 0x00002acecebc0700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 300 in wait
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 552 in wait
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 1156 in run
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x00002aceb559e700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 300 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/cacheMemoryManager.py", line 247 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/cacheMemoryManager.py", line 166 in run
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x00002ace2d422700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opTiffReader.py", line 170 in execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operator.py", line 591 in call_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/slot.py", line 869 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 682 in _wait_within_request
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 65 in execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operator.py", line 591 in call_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/slot.py", line 869 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 682 in _wait_within_request
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 150 in _fetch_and_store_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 112 in _execute_Output_impl
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 92 in copy_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute

Current thread 0x00002ace2b221700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opTiffReader.py", line 159 in execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operator.py", line 591 in call_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/slot.py", line 869 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 682 in _wait_within_request
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 65 in execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operator.py", line 591 in call_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/slot.py", line 869 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 682 in _wait_within_request
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 150 in _fetch_and_store_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 112 in _execute_Output_impl
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 92 in copy_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute

Thread 0x00002ace29020700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/site-packages/numpy/core/numeric.py", line 492 in asarray
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 63 in copy_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute

Thread 0x00002ace26e1f700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opTiffReader.py", line 170 in execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operator.py", line 591 in call_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/slot.py", line 869 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 682 in _wait_within_request
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 65 in execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operator.py", line 591 in call_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/slot.py", line 869 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 682 in _wait_within_request
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569 in _wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 150 in _fetch_and_store_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 112 in _execute_Output_impl
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 92 in copy_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute

Thread 0x00002ace24c1e700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/site-packages/numpy/core/numeric.py", line 492 in asarray
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 63 in copy_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute

Thread 0x00002ace22a1d700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/linecache.py", line 137 in updatecache
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/linecache.py", line 47 in getlines
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/linecache.py", line 16 in getline
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/traceback.py", line 285 in line
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/traceback.py", line 363 in extract
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/traceback.py", line 508 in __init__
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/traceback.py", line 104 in print_exception
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 101 in log_exception
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 263 in _handleFailedRequest
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 80 in __call__
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 381 in _post_execute
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 371 in _execute

Thread 0x00002ace2081c700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/site-packages/numpy/core/numeric.py", line 492 in asarray
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 63 in copy_block
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360 in _execute

Thread 0x00002ace1e61b700 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 296 in wait
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/local/biotools/ilastik/1.3.3/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x00002acdc36f8ec0 (most recent call first):
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 70 in startShellGui
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/ilastik/ilastik_main.py", line 171 in main
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/ilastik/ilastik.py", line 128 in main
  File "/usr/local/biotools/ilastik/1.3.3/ilastik-meta/ilastik/ilastik.py", line 134 in <module>
/usr/local/biotools/ilastik/1.3.3/run_ilastik.sh: line 77: 85017 Segmentation fault      "${PREFIX}/bin/python" "${PREFIX}/ilastik-meta/ilastik/ilastik.py" "$@"
```

## Desktop (please complete the following information):
 - ilastik version: 1.3.3
 - OS: RHEL7

**Comment by raymond301** [comment] 2020-06-12 18:03
I've figured out how to use headless mode...and it does work through that method.
So....perhaps I could change my request to "Can you add something to FAQ or documentation that denotes troubleshooting segmentation fault errors by switching modes?"

Thank you for this great software.

**Comment by k-dominik** [comment] 2020-06-17 13:24
Hi @raymond301,

thank you very much for the report and also for the update on what worked for you. Segmentation faults are in general not easy to debug. That it works for you in headless means that the cause _might_ be rooted in Qt. But again. This is not always the case. I would rather try finding the root cause of this than adding this to our faq, as it might or might not help, in general. Would you be willing to share the project as well as the "offending" file with us (in order to make it run in gui we would also need all the training files, too).

**Comment by k-dominik** [comment] 2020-07-27 14:36
closing this with no way of reproducing it. Might be down to specific dependency combination in 1.3.3.

**Closed by k-dominik** 2020-07-27 14:36 UTC
