### ISSUE TITLE
Export as multipage tiff generates error message

### ISSUE THREAD

**Issue by arndroth** [ilastik/ilastik#1572] opened 2017-08-08 16:55 UTC
Exporting a 3D dataset of labels to a multipage tiff file generates the following error message:

Failed to export layer due to the following error:

Precondition violation!
Unable to open file 'D:/Arnd/filename.tiff'. (This is the multipage tiff output file, which is generated anyway.)
(C:\conda3\conda-bld\work\src\impex\tiff.cxx:839)

This error occurs in version 1.2.2rc4 and 1.2.2rc3 on Windows.

**Comment by k-dominik** [comment] 2017-08-10 20:05
Hi @arndroth ,

it's really unfortunate that you are experiencing issues using ilastik. Could you give us a few more details on the issue? How many channels does your image have? How large are those images?

If you are exporting the tiffs for use in Fiji, you could also export to `h5` and import the files into Fiji using the [import/export plugin in Fiji](http://ilastik.org/documentation/fiji_export/plugin).

Cheers
Dominik

**Comment by arndroth** [comment] 2017-08-11 14:33
Hi Dominik,

thank you for your rapid reply. The volume of labels I'm trying to export is small (273 voxels in z, 557 in y and 569 in x), there is one channel, and I'm converting to data type unsigned 8-bit. I will send you a screenshot by email.

The bug is probably related to the bug reported by Anna Kreshuk here https://github.com/ilastik/ilastik/issues/1534

The behaviour is probabilistic: on successive trials, the error message appears after a variable amount of time, correlated with the number of z slices that are written to the multipage tiff file. Sometimes the error appears after a small fraction of a second and only 10 or so slices are written to the file, sometimes the error appears after more than a second and 150 or so slices are written to the file. Sometimes the entire file is written successfully and no error message appears.

I realize that this bug is only a nuisance, but it is likely to affect many users.

Best wishes,

Arnd

**Comment by emilmelnikov** [comment] 2019-02-13 16:32
Closing this issue: cannot reproduce the error.

See #1534 for more information.

**Closed by emilmelnikov** 2019-02-13 16:32 UTC
