### ISSUE TITLE
Error in MemUsageDialog

### ISSUE THREAD

**Issue by christophdecker** [ilastik/ilastik#1072] opened 2015-01-19 13:05 UTC
Appeared in object prediction export applet when trying to access the memory usage dialog. Version info: Pulled ilastik/volumina/lazyflow/vigra a couple of hours ago.

```
INFO 2015-01-19 13:49:05,427 arrayCacheMemoryMgr 27064 140662175422208 freeing memory...
INFO 2015-01-19 13:49:51,640 arrayCacheMemoryMgr 27064 140662175422208 freed 93/93 blocks, new usage = 91.296392%
INFO 2015-01-19 13:50:04,173 arrayCacheMemoryMgr 27064 140662175422208 freeing memory...
INFO 2015-01-19 13:50:50,008 arrayCacheMemoryMgr 27064 140662175422208 freed 127/127 blocks, new usage = 91.750442%
ERROR 2015-01-19 13:50:53,682 excepthooks 27064 140663390709568 Unhandled exception in thread: 'MainThread'
ERROR 2015-01-19 13:50:53,734 excepthooks 27064 140663390709568 Traceback (most recent call last):
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/ilastik/ilastik/shell/gui/ilastikShell.py", line 687, in showMemUsageDialog
    self._memDlg = MemUsageDialog()
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/ilastik/ilastik/shell/gui/memUsageDialog.py", line 51, in __init__
    self._updateReport()
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/ilastik/ilastik/shell/gui/memUsageDialog.py", line 58, in _updateReport
    c.generateReport(r)
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/lazyflow/lazyflow/operators/opSlicedBlockedArrayCache.py", line 74, in generateReport
    iOp.generateReport(n)
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/lazyflow/lazyflow/operators/opBlockedArrayCache.py", line 211, in generateReport
    block.generateReport(n)
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/lazyflow/lazyflow/operators/opArrayCache.py", line 136, in generateReport
    report.fractionOfUsedMemoryDirty = self.fractionOfUsedMemoryDirty()
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/lazyflow/lazyflow/operators/opArrayCache.py", line 124, in fractionOfUsedMemoryDirty
    sh = self._blockShapeForIndex(i)
  File "/home/cdecker/software/ilastik-1.1.3-Linux/src/ilastik/lazyflow/lazyflow/operators/opArrayCache.py", line 113, in _blockShapeForIndex
    blockStop = numpy.minimum(blockStart + self._blockShape, cacheShape)
ValueError: operands could not be broadcast together with shapes (8) (4) 
```

**Comment by burgerdev** [comment] 2015-02-12 07:41
duplicate of #1050

**Closed by burgerdev** 2015-02-12 07:41 UTC
Labels: bug, shell
