### ISSUE TITLE
Changes in preprocessing remove seeds

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#918] opened 2014-06-24 08:41 UTC
User report:

I encountered errors after changing the values on the Preprocessing tab
of the Carving workflow.  I had labeled and segmented two object
already, saved them and the entire project, then changed "dark lines
(inverted, smoothed)" to "dark lines (valley)" and the "filter scale"
value.  I had to uncheck "write protect".

I had expected that the original labels would be preserved, but the
exact segmentation lost (just need to recreate it).  I got the following
errors ("IndexError: index 266034 is out of bounds for size 259728")
when selecting the Labelling tab.

I was able to re-Segment the two objects and get rid of those errors.
(After saving the objects I was also able to save the project without
error).

Would it be possible to remove the computed values (segmentations)
dependent on the old Preprocessing values (but keep the labels) to
prevent the errors?

**Comment by btbest** [comment] 2023-02-13 09:30
As of #2664, we now discard all saved objects when the user changes preprocessing. The user is warned about this before they re-execute preprocessing.

We could consider keeping the labels of saved objects and discarding only their segmentations, but doing this properly will require reworking the handling of saved objects quite a bit. One would also need to extend Carving with a sub-workflow to guide the user to re-segment all saved objects after changing preprocessing. The user would have to do this manually for each object. And they _should_ do it manually, as it's not sound to just assume that all saved labels are semantically valid with the new preprocessing.

(Also this is a dupe of #2011)

**Closed by btbest** 2023-02-13 09:30 UTC
Labels: bug, carving
